[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"

[project]
name = "trading_ig_core"
version = "0.0.01"
description = "A lightweight Python wrapper for the IG Markets API"
authors = [
    { name = "Femto Trader", email = "femto.trader@gmail.com" },
    { name = "Andy Geach", email = "andy@bugorfeature.net" },
    { name = "Mat Tolladay", email = "djlets2004@yahoo.co.uk"},
]
requires-python = ">=3.13,<4"
readme = "README.md"
license = "BSD-3-Clause"
dependencies = [
    "cryptography",
    "requests",
    "lightstreamer-client-lib>=1.0.3",
    "pandas",
    "pydantic",
]

[dependency-groups]
dev = [
    "ruff",
    "pytest",
]

[tool.pytest.ini_options]
log_cli = true
pythonpath = ["."]
testpaths = ["tests",]

[tool.uv.build-backend]
module-name = "trading_ig_core"
module-root = ""

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".github",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
]
line-length = 100
indent-width = 4

[tool.ruff.lint]
ignore = []
fixable = ["ALL"]
extend-select = ["B","E","F","I","Q"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"